-- Seed counties data with custom ordering (first 8, then alphabetical)
INSERT INTO counties (name, sort_order) VALUES
-- First 8 counties in specified order
('Nairobi', 1),
('Kiambu', 2),
('Kajiado', 3),
('Machakos', 4),
('Mombasa', 5),
('Kisumu', 6),
('Nakuru', 7),
('Uasin Gishu', 8),
-- Remaining counties alphabetically
('Baringo', 9),
('Bomet', 10),
('Bungoma', 11),
('Busia', 12),
('Elgeyo Marakwet', 13),
('Embu', 14),
('Garissa', 15),
('Homa Bay', 16),
('Isiolo', 17),
('Kakamega', 18),
('Kericho', 19),
('Kirinyaga', 20),
('Kisii', 21),
('Kitui', 22),
('Kwale', 23),
('Laikipia', 24),
('Lamu', 25),
('Mandera', 26),
('Marsabit', 27),
('Meru', 28),
('Migori', 29),
('Makueni', 30),
('Muranga', 31),
('Narok', 32),
('Nandi', 33),
('Nyamira', 34),
('Nyandarua', 35),
('Nyeri', 36),
('Samburu', 37),
('Siaya', 38),
('Taita Taveta', 39),
('Tana River', 40),
('Tharaka Nithi', 41),
('Trans Nzoia', 42),
('Turkana', 43),
('Vihiga', 44),
('Wajir', 45),
('West Pokot', 46);

-- Sample subcounties for major counties
INSERT INTO subcounties (county_id, name) VALUES
-- Nairobi subcounties
(1, 'Westlands'),
(1, 'Dagoretti North'),
(1, 'Dagoretti South'),
(1, 'Langata'),
(1, 'Kibra'),
(1, 'Roysambu'),
(1, 'Kasarani'),
(1, 'Ruaraka'),
(1, 'Embakasi South'),
(1, 'Embakasi North'),
(1, 'Embakasi Central'),
(1, 'Embakasi East'),
(1, 'Embakasi West'),
(1, 'Makadara'),
(1, 'Kamukunji'),
(1, 'Starehe'),
(1, 'Mathare'),

-- Kiambu subcounties
(2, 'Thika Town'),
(2, 'Ruiru'),
(2, 'Juja'),
(2, 'Gatundu South'),
(2, 'Gatundu North'),
(2, 'Githunguri'),
(2, 'Kiambu'),
(2, 'Kiambaa'),
(2, 'Kabete'),
(2, 'Kikuyu'),
(2, 'Limuru'),
(2, 'Lari'),

-- Mombasa subcounties
(5, 'Changamwe'),
(5, 'Jomba'),
(5, 'Kisauni'),
(5, 'Nyali'),
(5, 'Likoni'),
(5, 'Mvita');
